version: "3.8"

services:
  postgres:
    image: 'postgres:16-alpine'
    container_name: postgres
    restart: unless-stopped
    ports:
        - 5432:5432
    environment:
        POSTGRES_DB: ${DB_NAME}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASS}
        PGDATA: /opt/postgres
    volumes:
        - .docker/postgres:/opt/postgres:Z
    networks:
        default:

  express-web:
    build: .
    container_name: express-web
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    networks:
        default:

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 8080:80
    depends_on:
      - express-web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:Z
    networks:
      default:
